
#important variables to store for housing ml

feature_to_drop_names = ['2ndFlrSF', 'GarageYrBlt', 'EnclosedPorch', '3SsnPorch', 'PoolArea', 'MiscVal', 'MSSubClass_40', 'MSSubClass_45', 'MSSubClass_70', 'MSSubClass_80', 'MSSubClass_85', 'MSSubClass_160', 'MSSubClass_180', 'MSZoning_RH', 'MSZoning_RM', 'Alley_No_Alley', 'Alley_Pave','LotShape_IR2', 'LotShape_IR3', 'LandContour_Low', 'LotConfig_FR3', 'LandSlope_Mod', 'LandSlope_Sev', 'Neighborhood_Blueste', 'Neighborhood_BrDale', 'Neighborhood_ClearCr', 'Neighborhood_MeadowV', 'Neighborhood_NPkVill', 'Neighborhood_SWISU', 'Condition1_Feedr', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn', 'BldgType_2fmCon', 'HouseStyle_1.5Unf', 'HouseStyle_2.5Fin', 'HouseStyle_2.5Unf', 'HouseStyle_2Story', 'HouseStyle_SFoyer', 'HouseStyle_SLvl', 'RoofStyle_Gambrel', 'RoofStyle_Hip', 'RoofStyle_Shed', 'RoofMatl_CompShg', 'RoofMatl_Membran', 'RoofMatl_Metal', 'RoofMatl_Roll', 'RoofMatl_Tar&Grv', 'RoofMatl_WdShake', 'Exterior1st_AsphShn', 'Exterior1st_BrkComm', 'Exterior1st_CBlock', 'Exterior1st_CemntBd', 'Exterior1st_ImStucc', 'Exterior1st_Stone', 'Exterior1st_VinylSd', 'Exterior1st_WdShing', 'Exterior2nd_AsphShn', 'Exterior2nd_Brk Cmn', 'Exterior2nd_CBlock', 'Exterior2nd_HdBoard', 'Exterior2nd_ImStucc', 'Exterior2nd_MetalSd', 'Exterior2nd_Other', 'Exterior2nd_Stucco', 'Exterior2nd_Wd Sdng', 'Exterior2nd_Wd Shng', 'MasVnrType_BrkFace', 'Foundation_Slab', 'Foundation_Stone', 'Foundation_Wood', 'BsmtFinType1_No_Bsmt', 'BsmtFinType1_Unf', 'BsmtFinType2_No_Bsmt', 'Heating_GasA', 'Heating_GasW', 'Heating_Grav', 'Heating_OthW', 'Heating_Wall', 'Electrical_FuseF', 'Electrical_FuseP', 'Electrical_Mix', 'Functional_Maj2', 'Functional_Min1', 'Functional_Min2', 'Functional_Mod', 'Functional_Sev', 'GarageType_Detchd', 'Fence_GdWo', 'Fence_MnWw', 'Fence_No_Fence', 'MiscFeature_No_MF', 'MiscFeature_Othr', 'MiscFeature_Shed', 'MiscFeature_TenC', 'SaleType_Con', 'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth',	'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'MoSold_3', 'MoSold_9', 'MoSold_11', 'MoSold_12', 'YrSold_2007', 'ExterCond_Fa', 'ExterCond_Po', 'ExterCond_TA', 'BsmtQual_No_Bsmt', 'BsmtCond_Gd', 'BsmtCond_No_Bsmt', 'BsmtCond_Po', 'BsmtExposure_Mn', 'BsmtExposure_No_Bsmt', 'HeatingQC_Po', 'FireplaceQu_Gd', 'FireplaceQu_Po', 'GarageQual_Gd', 'GarageQual_Po', 'GarageQual_TA', 'GarageCond_Gd', 'GarageCond_Po', 'GarageCond_TA', 'PoolQC_Fa', 'PoolQC_Gd', 'PoolQC_No_Pool']

continous_features = ['LotFrontage','LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch', 'ScreenPorch','PoolArea','MiscVal','YearBuilt','YearRemodAdd','GarageYrBlt']

categories = ['MSSubClass','MSZoning','Street','Alley','LotShape','LandContour','LotConfig',
             'LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl',
             'Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond',
             'BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical',
             'KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive',
             'PoolQC','Fence','MiscFeature','SaleType','SaleCondition','MoSold','YrSold']