In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
%matplotlib inline

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)

#imputer.py must be in directory
#please look at doc_strings for HousingImpute class
import jj_imputer

In [2]:
housing = jj_imputer.HousingImpute('train.csv')

LotFrontage 259
Alley 1369
MasVnrType 8
MasVnrArea 8
BsmtQual 37
BsmtCond 37
BsmtExposure 38
BsmtFinType1 37
BsmtFinType2 38
Electrical 1
FireplaceQu 690
GarageType 81
GarageYrBlt 81
GarageFinish 81
GarageQual 81
GarageCond 81
PoolQC 1453
Fence 1179
MiscFeature 1406


In [3]:
housing.run_imputers()

MasVnrArea imputer embedded in another imputer
BsmtCond imputer embedded in another imputer
BsmtExposure imputer embedded in another imputer
BsmtFinType1 imputer embedded in another imputer
BsmtFinType2 imputer embedded in another imputer
GarageYrBlt imputer embedded in another imputer
GarageFinish imputer embedded in another imputer
GarageQual imputer embedded in another imputer
GarageCond imputer embedded in another imputer


In [4]:
housing.left_to_impute()

BsmtExposure 1
--------------------
Id
949    NaN
Name: BsmtExposure, dtype: object
--------------------
BsmtFinType2 1
--------------------
Id
333    NaN
Name: BsmtFinType2, dtype: object
--------------------


indx 949 has NaN BsmtExposure but a basement condition/qual with 0 finished area. Will impute as 'No'

In [5]:
housing.df.loc[949, 'BsmtExposure'] = 'No'


index 333 is imputed as Rec via median value since the missing competely at random BsmFinType2 value .

In [6]:
housing.df.loc[333, 'BsmtFinType2'] = 'Rec'

In [7]:
housing.df.sample(20)

MSSubClass MSZoning  LotFrontage  LotArea Street     Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea   PoolQC     Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
Id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
1423         120       RM    37.000000     4435   Pave  No_Alley      Reg         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm   TwnhsE     1Story            6            5       2003          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace       170.0        Gd        TA      PConc       Gd       TA           Av          GLQ         686          Unf           0        162          848    GasA        Ex          Y      SBrkr       848         0             0        848             1             0         1         0             1             1          Gd             3        Typ           0       No_FP     Attchd       2003.0          Fin           2         420         TA         TA          Y         140            0              0          0            0         0  No_Pool  No_Fence       No_MF        0       3    2008       WD        Normal     136500
1190          60       RL    60.000000     7500   Pave  No_Alley      Reg         Lvl    AllPub    Inside       Gtl      Gilbert       Norm       Norm     1Fam     2Story            7            5       1999          1999     Gable  CompShg     VinylSd     VinylSd       None         0.0        TA        TA      PConc       TA       TA           No          Unf           0          Unf           0        994          994    GasA        Gd          Y      SBrkr      1028       776             0       1804             0             0         2         1             3             1          Gd             7        Typ           1          TA     Attchd       1999.0          Fin           2         442         TA         TA          Y         140           60              0          0            0         0  No_Pool  No_Fence       No_MF        0       6    2010       WD        Normal     189000
142           20       RL    78.000000    11645   Pave  No_Alley      Reg         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     1Story            7            5       2005          2005     Gable  CompShg     VinylSd     VinylSd       None         0.0        Gd        TA      PConc       Gd       TA           Av          GLQ        1300          Unf   

In [8]:
#final check for missing values
housing.left_to_impute()

The following three changes were made after further EDA and placed here to merge copies of train_imputed.csv

In [9]:
housing.df.drop('Utilities', axis=1, inplace=True)
#drop utilities since 1459 out of 1600 share same value
housing.df.drop('TotalBsmtSF', axis=1, inplace=True)
#drop TotalBsmtSF for multicollinearity since it is the sum of the 3 other BsmtSF columns

housing.df.loc[:,'Exterior2nd'].replace('CmentBd','CemntBd', inplace=True)
#correcting for spelling errors to make the types of values in Exterior1st and Exterior2nd the same

In [10]:
housing.save_df('train_imputed')